# Generated by Django 3.0.4 on 2020-04-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyprinted', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='creator',
            field=models.CharField(max_length=200),
        ),
    ]
