# Generated by Django 3.0.4 on 2020-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyprinted', '0002_auto_20200401_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='last_name',
            field=models.CharField(default='bansal', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='creator',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
