# Generated by Django 3.0.4 on 2020-04-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyprinted', '0003_auto_20200401_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='last_paradigm',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='paradigm',
            field=models.CharField(max_length=2000),
        ),
    ]
